name: Build And Push Plugin Api

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Add nuget source
        run: dotnet nuget add source --username FlurinBruehwiler --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Joa-Launcher/index.json"
      - name: Pack
        run: dotnet pack --configuration Release
      - name: Push github.com
        run: dotnet nuget push "bin/Release/JoaLauncher.Api.1.0.0.nupkg" --source "github"
      - name: Push nuget.org
        if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
        run: dotnet nuget push "bin/Release/JoaLauncher.Api.1.0.0.nupkg" --api-key ${{secrets.NUGET_ORG_API_KEY}} --source https://api.nuget.org/v3/index.json
